export const sidebarList = [
  {
    colorClick: false,
    id: 1,
    title: "New",
    iconClass: "fa-solid fa-house",
    color: true,
  },
  { colorClick: false, id: 2, title: "Coding", iconClass: "fa-solid fa-code" },
  { colorClick: false, id: 3, title: "ReactJS", iconClass: "fa-solid fa-code" },
  { colorClick: false, id: 4, title: "NextJS", iconClass: "fa-solid fa-code" },
  { colorClick: false, id: 5, title: "Music", iconClass: "fa-solid fa-music" },
  {
    colorClick: false,
    id: 6,
    title: "Education",
    iconClass: "fa-solid fa-graduation-cap",
  },
  {
    colorClick: false,
    id: 7,
    title: "Podcast",
    iconClass: "fa-solid fa-podcast",
  },
  { colorClick: false, id: 8, title: "Movie", iconClass: "fa-solid fa-film" },
  {
    colorClick: false,
    id: 9,
    title: "Gaming",
    iconClass: "fa-solid fa-gamepad",
  },
  {
    colorClick: false,
    id: 10,
    title: "Live",
    iconClass: "fa-solid fa-display",
  },
  {
    colorClick: false,
    id: 11,
    title: "Sport",
    iconClass: "fa-solid fa-dumbbell",
  },
  {
    colorClick: false,
    id: 12,
    title: "Fashion",
    iconClass: "fa-solid fa-shirt",
  },
  {
    colorClick: false,
    id: 13,
    title: "Beauty",
    iconClass: "fa-regular fa-gem",
  },
  {
    colorClick: false,
    id: 14,
    title: "Comedy",
    iconClass: "fa-solid fa-masks-theater",
  },
  {
    colorClick: false,
    id: 15,
    title: "Gym",
    iconClass: "fa-solid fa-dumbbell",
  },
  {
    colorClick: false,
    id: 16,
    title: "Crypto",
    iconClass: "fa-brands fa-bitcoin",
  },
];
